auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Nova's Blog
url:              http://novawoo.github.io
feed:             /atom.xml
author:
    name:         NovaWoo
    twitter:      twitter.com/beiyuu
description:      "Nova\'s Blog"
author_info:      <a href="http://novawoo.github.io/about">Nova Woo</a>

lsi:              false
copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; 2013
